#! /bin/sh

xsetroot -cursor_name left_ptr &
feh --bg-scale ~/Pictures/background.jpg &
bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a mpv floating=true center=true border=false
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
sxhkd -c /home/cuong/.config/bspwm/sxhkdrc &

/home/cuong/.config/bspwm/panel &
